apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-appsettings
  app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "{{ .Values.clientDefaultLogLevel }}"
        }
      },
      "AppUrl": "{{ .Values.clientAppUrl }}",
      "DemoLogin": {
        "BaseAddress": "{{ .Values.clientDemoLoginBaseAddress }}",
        "ClientId": "{{ .Values.clientDemoLoginClientId }}",
        "ClientSecret": "{{ .Values.clientDemoLoginClientSecret }}",
        "UserName": "{{ .Values.clientDemoLoginUserName }}",
        "Password": "{{ .Values.clientDemoLoginPassword }}"
      },
      "ApplicationInsights": {
        "ConnectionString": "{{ .Values.clientApplicationInsightsConnectionString }}"
      }
    }
