apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ravendb-ingress-route
  namespace: ravendb
  labels:
    app.kubernetes.io/name: ravendb
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  entryPoints:
    - websecure
  routes:
    {{- range .Values.nodeTags }}
    - match: HostSNI(`{{ lower . }}.{{$.Values.domain}}`)
      services:
      - name: ravendb-{{ . | lower}}
        port: 8080
        terminationDelay: 400
    - match: HostSNI(`{{ lower . }}-tcp.{{$.Values.domain}}`)
      services:
      - name: ravendb-{{ . | lower}}
        port: 38888
        terminationDelay: 400
    {{- end }}
  tls:
    passthrough: true
