kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: temp-local-storage
  namespace: ravendb
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-disk
  volumeBindingMode: Immediate
  resources:
    requests:
      storage: 20Gi
