{{- if .Values.ingressRouteTCP.enabled -}}
{{- $fullName := include "opus.fullname" . -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ $fullName }}
  namespace: traefik
  {{- with .Values.ingressRouteTCP.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- with .Values.ingressRouteTCP.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  entryPoints:
  {{- range .Values.ingressRouteTCP.entryPoints }}
  - {{ . }}
  {{- end }}
  routes:
  - match: HostSNI(`mqtt.{{$.Values.domain}}`)
    services:
    - name: mqtt-iot
      port: 8883
      terminationDelay: 400
  tls:
    passthrough: true
{{- end }}